export enum TYPES {
  /* WORKS */
  GET_WORKS_LIST = 'GET_WORKS_LIST',
  DELETE_WORK = 'DELETE_WORK',
  POST_WORK_CREATE = 'POST_WORK_CREATE',
  PUT_WORK_UPDATE = 'PUT_WORK_UPDATE',
  GET_WORK_DETAIL = 'GET_WORK_DETAIL',
}
